# Generated by Django 2.2 on 2019-06-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.TextField(default='This is  a body of a comment'),
            preserve_default=False,
        ),
    ]
