# Generated by Django 2.2 on 2019-06-14 19:14

import app_posts.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_posts', '0002_content_file_image_text_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='content',
            name='order',
            field=app_posts.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
