# Generated by Django 2.2 on 2019-06-16 08:17

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_posts', '0003_auto_20190614_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=imagekit.models.fields.ProcessedImageField(upload_to='images'),
        ),
    ]
