# Generated by Django 2.2 on 2019-06-16 10:36

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_posts', '0004_auto_20190616_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postavatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='postavatars/%Y/%m/%d/'),
        ),
    ]
