# Generated by Django 2.2 on 2019-06-11 08:48

import app_courses.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_courses', '0002_content_file_image_text_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='content',
            name='order',
            field=app_courses.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=app_courses.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
